package null;

import com.edgar.core.repository.Persistable;
import javax.validation.constraints.Null;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.hibernate.validator.constraints.NotEmpty;
import javax.validation.groups.Default;
import com.google.common.base.MoreObjects;

/**
 * This class is generated by Jdbc code generator.
 *
 * @author Jdbc Code Generator
 */
public class Course implements Persistable<Integer> {

	private static final long serialVersionUID = 1L;

	@NotNull(groups = {Default.class, Default.class})
	private int courseId;

	private int courseSumId;

	@NotEmpty
	@Size(max=128)
	private String courseName = "-";

	@NotEmpty
	@Size(max=140)
	private String description = "-";

	@NotNull
	private int courseTime = 0;

	private int courseType = 1;

	@Size(max=256)
	private String coursePath;

	private int isLocal = 1;

	private int occupation = 1;

	private int applicationLevel = 1;

	public Course() {

	}

	@Override
	public Integer getId () {
		return this.courseId;
	}

	@Override
	public void setId(Integer id) {
		this.courseId = id;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseSumId(int courseSumId) {
		this.courseSumId = courseSumId;
	}

	public int getCourseSumId() {
		return this.courseSumId;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	public String getCourseName() {
		return this.courseName;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDescription() {
		return this.description;
	}

	public void setCourseTime(int courseTime) {
		this.courseTime = courseTime;
	}

	public int getCourseTime() {
		return this.courseTime;
	}

	public void setCourseType(int courseType) {
		this.courseType = courseType;
	}

	public int getCourseType() {
		return this.courseType;
	}

	public void setCoursePath(String coursePath) {
		this.coursePath = coursePath;
	}

	public String getCoursePath() {
		return this.coursePath;
	}

	public void setIsLocal(int isLocal) {
		this.isLocal = isLocal;
	}

	public int getIsLocal() {
		return this.isLocal;
	}

	public void setOccupation(int occupation) {
		this.occupation = occupation;
	}

	public int getOccupation() {
		return this.occupation;
	}

	public void setApplicationLevel(int applicationLevel) {
		this.applicationLevel = applicationLevel;
	}

	public int getApplicationLevel() {
		return this.applicationLevel;
	}

	@Override
	public String toString() {
		return MoreObjects.toStringHelper("Course")
			.add("courseId", courseId)
			.add("courseSumId", courseSumId)
			.add("courseName", courseName)
			.add("description", description)
			.add("courseTime", courseTime)
			.add("courseType", courseType)
			.add("coursePath", coursePath)
			.add("isLocal", isLocal)
			.add("occupation", occupation)
			.add("applicationLevel", applicationLevel)
			.toString();
	}

	/* START 写在START和END中间的代码不会被替换*/

	/* END 写在START和END中间的代码不会被替换*/

}