package null;

import com.edgar.core.repository.BaseMapper;
import org.springframework.stereotype.Repository;
import org.slf4j.LoggerFactory;
import org.slf4j.Logger;
import null.CourseSum;

/**
 * This class is generated by Jdbc code generator.
 *
 * @author Jdbc Code Generator
 */
@Repository
public interface CourseSumMapper extends BaseMapper<CourseSum, Integer> {

	final static Logger logger = LoggerFactory.getLogger (CourseSumMapper.class);

	/* START 写在START和END中间的代码不会被替换*/

	/* END 写在START和END中间的代码不会被替换*/

}

