package null;

import com.edgar.core.repository.Persistable;
import javax.validation.constraints.Null;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.hibernate.validator.constraints.NotEmpty;
import javax.validation.groups.Default;
import com.google.common.base.MoreObjects;

/**
 * This class is generated by Jdbc code generator.
 *
 * @author Jdbc Code Generator
 */
public class CourseSum implements Persistable<Integer> {

	private static final long serialVersionUID = 1L;

	@NotNull(groups = {Default.class, Default.class})
	private int courseSumId;

	@NotNull
	private int occupation = 1;

	@NotNull
	private int applicationLevel = 1;

	@NotNull
	private int courseTime = 0;

	@NotNull
	private int courseCount = 0;

	public CourseSum() {

	}

	@Override
	public Integer getId () {
		return this.courseSumId;
	}

	@Override
	public void setId(Integer id) {
		this.courseSumId = id;
	}

	public void setCourseSumId(int courseSumId) {
		this.courseSumId = courseSumId;
	}

	public int getCourseSumId() {
		return this.courseSumId;
	}

	public void setOccupation(int occupation) {
		this.occupation = occupation;
	}

	public int getOccupation() {
		return this.occupation;
	}

	public void setApplicationLevel(int applicationLevel) {
		this.applicationLevel = applicationLevel;
	}

	public int getApplicationLevel() {
		return this.applicationLevel;
	}

	public void setCourseTime(int courseTime) {
		this.courseTime = courseTime;
	}

	public int getCourseTime() {
		return this.courseTime;
	}

	public void setCourseCount(int courseCount) {
		this.courseCount = courseCount;
	}

	public int getCourseCount() {
		return this.courseCount;
	}

	@Override
	public String toString() {
		return MoreObjects.toStringHelper("CourseSum")
			.add("courseSumId", courseSumId)
			.add("occupation", occupation)
			.add("applicationLevel", applicationLevel)
			.add("courseTime", courseTime)
			.add("courseCount", courseCount)
			.toString();
	}

	/* START 写在START和END中间的代码不会被替换*/

	/* END 写在START和END中间的代码不会被替换*/

}