package null;

import com.edgar.core.repository.Persistable;
import javax.validation.constraints.Null;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.hibernate.validator.constraints.NotEmpty;
import javax.validation.groups.Default;
import com.google.common.base.MoreObjects;

/**
 * This class is generated by Jdbc code generator.
 *
 * @author Jdbc Code Generator
 */
public class ExaminationResult implements Persistable<Integer> {

	private static final long serialVersionUID = 1L;

	@NotNull(groups = {Default.class, Default.class})
	private int examinationId;

	private int applicantId;

	@NotNull
	private int examinationType = 1;

	@NotNull
	private int examinationCat = 1;

	@NotEmpty
	@Size(max=18)
	private String examinationCertificateNo = "-";

	@NotNull
	private float theroyScore = 0.0F;

	@NotNull
	private int theroyGrade = 1;

	@NotNull
	private float handleScore = 0.0F;

	@NotNull
	private int handleGrade = 1;

	@NotNull
	private int grade = 1;

	@NotEmpty
	@Size(max=10)
	private String examinationNo = "-";

	@NotNull
	private long gradeTime = 0L;

	@Size(max=8)
	private String fullname;

	private int gender = 1;

	private int identityType = 1;

	@Size(max=18)
	private String identityNo = "-";

	private int occupation = 1;

	private int applicationLevel = 1;

	public ExaminationResult() {

	}

	@Override
	public Integer getId () {
		return this.examinationId;
	}

	@Override
	public void setId(Integer id) {
		this.examinationId = id;
	}

	public void setExaminationId(int examinationId) {
		this.examinationId = examinationId;
	}

	public int getExaminationId() {
		return this.examinationId;
	}

	public void setApplicantId(int applicantId) {
		this.applicantId = applicantId;
	}

	public int getApplicantId() {
		return this.applicantId;
	}

	public void setExaminationType(int examinationType) {
		this.examinationType = examinationType;
	}

	public int getExaminationType() {
		return this.examinationType;
	}

	public void setExaminationCat(int examinationCat) {
		this.examinationCat = examinationCat;
	}

	public int getExaminationCat() {
		return this.examinationCat;
	}

	public void setExaminationCertificateNo(String examinationCertificateNo) {
		this.examinationCertificateNo = examinationCertificateNo;
	}

	public String getExaminationCertificateNo() {
		return this.examinationCertificateNo;
	}

	public void setTheroyScore(float theroyScore) {
		this.theroyScore = theroyScore;
	}

	public float getTheroyScore() {
		return this.theroyScore;
	}

	public void setTheroyGrade(int theroyGrade) {
		this.theroyGrade = theroyGrade;
	}

	public int getTheroyGrade() {
		return this.theroyGrade;
	}

	public void setHandleScore(float handleScore) {
		this.handleScore = handleScore;
	}

	public float getHandleScore() {
		return this.handleScore;
	}

	public void setHandleGrade(int handleGrade) {
		this.handleGrade = handleGrade;
	}

	public int getHandleGrade() {
		return this.handleGrade;
	}

	public void setGrade(int grade) {
		this.grade = grade;
	}

	public int getGrade() {
		return this.grade;
	}

	public void setExaminationNo(String examinationNo) {
		this.examinationNo = examinationNo;
	}

	public String getExaminationNo() {
		return this.examinationNo;
	}

	public void setGradeTime(long gradeTime) {
		this.gradeTime = gradeTime;
	}

	public long getGradeTime() {
		return this.gradeTime;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	public String getFullname() {
		return this.fullname;
	}

	public void setGender(int gender) {
		this.gender = gender;
	}

	public int getGender() {
		return this.gender;
	}

	public void setIdentityType(int identityType) {
		this.identityType = identityType;
	}

	public int getIdentityType() {
		return this.identityType;
	}

	public void setIdentityNo(String identityNo) {
		this.identityNo = identityNo;
	}

	public String getIdentityNo() {
		return this.identityNo;
	}

	public void setOccupation(int occupation) {
		this.occupation = occupation;
	}

	public int getOccupation() {
		return this.occupation;
	}

	public void setApplicationLevel(int applicationLevel) {
		this.applicationLevel = applicationLevel;
	}

	public int getApplicationLevel() {
		return this.applicationLevel;
	}

	@Override
	public String toString() {
		return MoreObjects.toStringHelper("ExaminationResult")
			.add("examinationId", examinationId)
			.add("applicantId", applicantId)
			.add("examinationType", examinationType)
			.add("examinationCat", examinationCat)
			.add("examinationCertificateNo", examinationCertificateNo)
			.add("theroyScore", theroyScore)
			.add("theroyGrade", theroyGrade)
			.add("handleScore", handleScore)
			.add("handleGrade", handleGrade)
			.add("grade", grade)
			.add("examinationNo", examinationNo)
			.add("gradeTime", gradeTime)
			.add("fullname", fullname)
			.add("gender", gender)
			.add("identityType", identityType)
			.add("identityNo", identityNo)
			.add("occupation", occupation)
			.add("applicationLevel", applicationLevel)
			.toString();
	}

	/* START 写在START和END中间的代码不会被替换*/

	/* END 写在START和END中间的代码不会被替换*/

}