package null;

import com.edgar.core.repository.Persistable;
import javax.validation.constraints.Null;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.hibernate.validator.constraints.NotEmpty;
import javax.validation.groups.Default;
import com.google.common.base.MoreObjects;

/**
 * This class is generated by Jdbc code generator.
 *
 * @author Jdbc Code Generator
 */
public class ExaminationApplication implements Persistable<Integer> {

	private static final long serialVersionUID = 1L;

	@NotNull(groups = {Default.class, Default.class})
	private int examinationApplicationId;

	private int applicantId;

	@NotNull
	private int applicationType = 0;

	@Size(max=64)
	private String applicationPath;

	@NotNull
	private long applyTime = 0L;

	@NotNull
	private int status = 1;

	@NotNull
	private int occupation = 1;

	@NotNull
	private int applicationLevel = 1;

	@Size(max=8)
	private String fullname;

	private int gender = 1;

	private int identityType = 1;

	@Size(max=18)
	private String identityNo = "-";

	@Size(max=140)
	private String approvalOpinion;

	private long approvalTime;

	public ExaminationApplication() {

	}

	@Override
	public Integer getId () {
		return this.examinationApplicationId;
	}

	@Override
	public void setId(Integer id) {
		this.examinationApplicationId = id;
	}

	public void setExaminationApplicationId(int examinationApplicationId) {
		this.examinationApplicationId = examinationApplicationId;
	}

	public int getExaminationApplicationId() {
		return this.examinationApplicationId;
	}

	public void setApplicantId(int applicantId) {
		this.applicantId = applicantId;
	}

	public int getApplicantId() {
		return this.applicantId;
	}

	public void setApplicationType(int applicationType) {
		this.applicationType = applicationType;
	}

	public int getApplicationType() {
		return this.applicationType;
	}

	public void setApplicationPath(String applicationPath) {
		this.applicationPath = applicationPath;
	}

	public String getApplicationPath() {
		return this.applicationPath;
	}

	public void setApplyTime(long applyTime) {
		this.applyTime = applyTime;
	}

	public long getApplyTime() {
		return this.applyTime;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getStatus() {
		return this.status;
	}

	public void setOccupation(int occupation) {
		this.occupation = occupation;
	}

	public int getOccupation() {
		return this.occupation;
	}

	public void setApplicationLevel(int applicationLevel) {
		this.applicationLevel = applicationLevel;
	}

	public int getApplicationLevel() {
		return this.applicationLevel;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	public String getFullname() {
		return this.fullname;
	}

	public void setGender(int gender) {
		this.gender = gender;
	}

	public int getGender() {
		return this.gender;
	}

	public void setIdentityType(int identityType) {
		this.identityType = identityType;
	}

	public int getIdentityType() {
		return this.identityType;
	}

	public void setIdentityNo(String identityNo) {
		this.identityNo = identityNo;
	}

	public String getIdentityNo() {
		return this.identityNo;
	}

	public void setApprovalOpinion(String approvalOpinion) {
		this.approvalOpinion = approvalOpinion;
	}

	public String getApprovalOpinion() {
		return this.approvalOpinion;
	}

	public void setApprovalTime(long approvalTime) {
		this.approvalTime = approvalTime;
	}

	public long getApprovalTime() {
		return this.approvalTime;
	}

	@Override
	public String toString() {
		return MoreObjects.toStringHelper("ExaminationApplication")
			.add("examinationApplicationId", examinationApplicationId)
			.add("applicantId", applicantId)
			.add("applicationType", applicationType)
			.add("applicationPath", applicationPath)
			.add("applyTime", applyTime)
			.add("status", status)
			.add("occupation", occupation)
			.add("applicationLevel", applicationLevel)
			.add("fullname", fullname)
			.add("gender", gender)
			.add("identityType", identityType)
			.add("identityNo", identityNo)
			.add("approvalOpinion", approvalOpinion)
			.add("approvalTime", approvalTime)
			.toString();
	}

	/* START 写在START和END中间的代码不会被替换*/

	/* END 写在START和END中间的代码不会被替换*/

}