package null;

import com.edgar.core.repository.Persistable;
import javax.validation.constraints.Null;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.hibernate.validator.constraints.NotEmpty;
import javax.validation.groups.Default;

/**
 * This class is generated by Jdbc code generator.
 *
 * @author Jdbc Code Generator
 */
public class Product implements Persistable<String> {

	private static final long serialVersionUID = 1L;

	private int id;

	@Size(max=1000)
	private String description;

	public Product() {

	}

	@Override
	public String getId() {
		throw new UnsupportedOperationException("There is no primary key");
	}

	@Override
	public void setId(String id) {
		throw new UnsupportedOperationException("There is no primary key");
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getId() {
		return this.id;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDescription() {
		return this.description;
	}

	@Override
	public String toString() {
		return MoreObjects.toStringHelper("Product")
			.add("id", id)
			.add("description", description)
			.toString();
	}

	/* START 写在START和END中间的代码不会被替换*/

	/* END 写在START和END中间的代码不会被替换*/

}