package null;

import com.edgar.core.repository.Persistable;
import javax.validation.constraints.Null;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.hibernate.validator.constraints.NotEmpty;
import javax.validation.groups.Default;
import com.google.common.base.MoreObjects;

/**
 * This class is generated by Jdbc code generator.
 *
 * @author Jdbc Code Generator
 */
public class StudyHistorySum implements Persistable<Integer> {

	private static final long serialVersionUID = 1L;

	@NotNull(groups = {Default.class, Default.class})
	private int studyHistorySumId;

	private int applicantId;

	private int courseSumId;

	private int studyTime = 0;

	@NotNull
	private int studyCount = 0;

	private int courseTime = 0;

	@NotNull
	private int courseCout = 0;

	private int status = 1;

	private int occupation = 1;

	private int applicationLevel = 1;

	@Size(max=8)
	private String fullname;

	private int gender = 1;

	private int identityType = 1;

	@Size(max=18)
	private String identityNo = "-";

	public StudyHistorySum() {

	}

	@Override
	public Integer getId () {
		return this.studyHistorySumId;
	}

	@Override
	public void setId(Integer id) {
		this.studyHistorySumId = id;
	}

	public void setStudyHistorySumId(int studyHistorySumId) {
		this.studyHistorySumId = studyHistorySumId;
	}

	public int getStudyHistorySumId() {
		return this.studyHistorySumId;
	}

	public void setApplicantId(int applicantId) {
		this.applicantId = applicantId;
	}

	public int getApplicantId() {
		return this.applicantId;
	}

	public void setCourseSumId(int courseSumId) {
		this.courseSumId = courseSumId;
	}

	public int getCourseSumId() {
		return this.courseSumId;
	}

	public void setStudyTime(int studyTime) {
		this.studyTime = studyTime;
	}

	public int getStudyTime() {
		return this.studyTime;
	}

	public void setStudyCount(int studyCount) {
		this.studyCount = studyCount;
	}

	public int getStudyCount() {
		return this.studyCount;
	}

	public void setCourseTime(int courseTime) {
		this.courseTime = courseTime;
	}

	public int getCourseTime() {
		return this.courseTime;
	}

	public void setCourseCout(int courseCout) {
		this.courseCout = courseCout;
	}

	public int getCourseCout() {
		return this.courseCout;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getStatus() {
		return this.status;
	}

	public void setOccupation(int occupation) {
		this.occupation = occupation;
	}

	public int getOccupation() {
		return this.occupation;
	}

	public void setApplicationLevel(int applicationLevel) {
		this.applicationLevel = applicationLevel;
	}

	public int getApplicationLevel() {
		return this.applicationLevel;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	public String getFullname() {
		return this.fullname;
	}

	public void setGender(int gender) {
		this.gender = gender;
	}

	public int getGender() {
		return this.gender;
	}

	public void setIdentityType(int identityType) {
		this.identityType = identityType;
	}

	public int getIdentityType() {
		return this.identityType;
	}

	public void setIdentityNo(String identityNo) {
		this.identityNo = identityNo;
	}

	public String getIdentityNo() {
		return this.identityNo;
	}

	@Override
	public String toString() {
		return MoreObjects.toStringHelper("StudyHistorySum")
			.add("studyHistorySumId", studyHistorySumId)
			.add("applicantId", applicantId)
			.add("courseSumId", courseSumId)
			.add("studyTime", studyTime)
			.add("studyCount", studyCount)
			.add("courseTime", courseTime)
			.add("courseCout", courseCout)
			.add("status", status)
			.add("occupation", occupation)
			.add("applicationLevel", applicationLevel)
			.add("fullname", fullname)
			.add("gender", gender)
			.add("identityType", identityType)
			.add("identityNo", identityNo)
			.toString();
	}

	/* START 写在START和END中间的代码不会被替换*/

	/* END 写在START和END中间的代码不会被替换*/

}