package null;

import com.edgar.core.repository.Persistable;
import javax.validation.constraints.Null;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.hibernate.validator.constraints.NotEmpty;
import javax.validation.groups.Default;
import com.google.common.base.MoreObjects;

/**
 * This class is generated by Jdbc code generator.
 *
 * @author Jdbc Code Generator
 */
public class Test implements Persistable<Integer> {

	private static final long serialVersionUID = 1L;

	@NotNull(groups = {Default.class})
	@Null(groups = {Default.class})
	private int id;

	@Size(max=255)
	private String name;

	public Test() {

	}

	@Override
	public Integer getId () {
		return this.id;
	}

	@Override
	public void setId(Integer id) {
		this.id = id;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return this.name;
	}

	@Override
	public String toString() {
		return MoreObjects.toStringHelper("Test")
			.add("id", id)
			.add("name", name)
			.toString();
	}

	/* START 写在START和END中间的代码不会被替换*/

	/* END 写在START和END中间的代码不会被替换*/

}