package null;

import com.edgar.core.repository.Persistable;
import javax.validation.constraints.Null;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.hibernate.validator.constraints.NotEmpty;
import javax.validation.groups.Default;
import com.google.common.base.MoreObjects;

/**
 * This class is generated by Jdbc code generator.
 *
 * @author Jdbc Code Generator
 */
public class User implements Persistable<Integer> {

	private static final long serialVersionUID = 1L;

	@NotNull(groups = {Default.class, Default.class})
	private int userId;

	private int applicantId;

	private int roleId;

	@NotEmpty
	@Size(max=16)
	private String username;

	@NotEmpty
	@Size(max=16)
	private String fullname;

	@NotEmpty
	@Size(max=128)
	private String password;

	@NotEmpty
	@Size(max=128)
	private String salt;

	@NotNull
	private int organization = 1;

	@NotNull
	private int authority = 0;

	public User() {

	}

	@Override
	public Integer getId () {
		return this.userId;
	}

	@Override
	public void setId(Integer id) {
		this.userId = id;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setApplicantId(int applicantId) {
		this.applicantId = applicantId;
	}

	public int getApplicantId() {
		return this.applicantId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getUsername() {
		return this.username;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	public String getFullname() {
		return this.fullname;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPassword() {
		return this.password;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	public String getSalt() {
		return this.salt;
	}

	public void setOrganization(int organization) {
		this.organization = organization;
	}

	public int getOrganization() {
		return this.organization;
	}

	public void setAuthority(int authority) {
		this.authority = authority;
	}

	public int getAuthority() {
		return this.authority;
	}

	@Override
	public String toString() {
		return MoreObjects.toStringHelper("User")
			.add("userId", userId)
			.add("applicantId", applicantId)
			.add("roleId", roleId)
			.add("username", username)
			.add("fullname", fullname)
			.add("password", password)
			.add("salt", salt)
			.add("organization", organization)
			.add("authority", authority)
			.toString();
	}

	/* START 写在START和END中间的代码不会被替换*/

	/* END 写在START和END中间的代码不会被替换*/

}