package com.github.edgar615.test.codegen.domain;

import com.github.edgar615.util.validation.Rule;
import com.google.common.collect.ArrayListMultimap;
import com.google.common.collect.Multimap;

/**
* This class is generated by Jdbc code generator.
*
* Table : sys_user
*
* @author Jdbc Code Generator Date 2019-03-17
*/
public class SysUserRule {

    /**
    * 根据数据库生成的最长长度校验
    *
    * @return Multimap<String, Rule>
    */
    public static Multimap<String, Rule> maxLengthRule() {
        Multimap<String, Rule> rules = ArrayListMultimap.create();
        rules.put("companyCode",  Rule.maxLength(24));
        rules.put("username",  Rule.maxLength(60));
        rules.put("password",  Rule.maxLength(64));
        rules.put("tel",  Rule.maxLength(11));
        rules.put("mail",  Rule.maxLength(60));
        rules.put("fullname",  Rule.maxLength(32));
        rules.put("salt",  Rule.maxLength(128));
        rules.put("ext",  Rule.maxLength(1073741824));
        return rules;
    }

    /**
    * 根据数据库生成的必填项校验。
    * 在实际接口开发中，有些必填项是没有的，例如自动生成的主键开始会设置为null
    *
    * @return Multimap<String, Rule>
    */
    public static Multimap<String, Rule> requiredRule() {
        Multimap<String, Rule> rules = ArrayListMultimap.create();
        
        rules.put("sysUserId", Rule.required());
        return rules;
    }

   /* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/


}