package com.github.edgar615.test.codegen.dao;

import com.github.edgar615.test.codegen.domain.SysUser;
import com.github.edgar615.util.db.BaseDao;

/**
* This class is generated by Jdbc code generator.
*
* Table : sys_user
*
* @author Jdbc Code Generator Date 2019-03-17
*/
public interface SysUserDao extends BaseDao<Long, SysUser> {

   /* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/


}